// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FatSlack.Core")>]
[<assembly: AssemblyProductAttribute("FatSlack")>]
[<assembly: AssemblyDescriptionAttribute("Slack bot/app framework in F# for F#")>]
[<assembly: AssemblyVersionAttribute("0.0.7")>]
[<assembly: AssemblyFileVersionAttribute("0.0.7")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FatSlack.Core"
    let [<Literal>] AssemblyProduct = "FatSlack"
    let [<Literal>] AssemblyDescription = "Slack bot/app framework in F# for F#"
    let [<Literal>] AssemblyVersion = "0.0.7"
    let [<Literal>] AssemblyFileVersion = "0.0.7"
    let [<Literal>] AssemblyConfiguration = "Release"
