// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FatSlack")>]
[<assembly: AssemblyProductAttribute("FatSlack")>]
[<assembly: AssemblyDescriptionAttribute("Slack bot/app framework in F# for F#")>]
[<assembly: AssemblyVersionAttribute("0.1.3")>]
[<assembly: AssemblyFileVersionAttribute("0.1.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FatSlack"
    let [<Literal>] AssemblyProduct = "FatSlack"
    let [<Literal>] AssemblyDescription = "Slack bot/app framework in F# for F#"
    let [<Literal>] AssemblyVersion = "0.1.3"
    let [<Literal>] AssemblyFileVersion = "0.1.3"
    let [<Literal>] AssemblyConfiguration = "Release"
